In [8]:
num1= int(input("Enter first number : "))
num2= int(input("Enter second number : "))
sum= num1+num2
print(sum)

Enter first number : 1234567
Enter second number : 567890
1802457


In [13]:
print(" Hi", "!", end="||")
print("Lashitha Vishnu Priya")

 Hi !||Lashitha Vishnu Priya


In [11]:
num= int(input("Enter a number : "))
if num%2==0:
    print(num," is an even number")
else:
    print(num," is an odd number")

Enter a number : 78
78  is an even number


In [33]:
num= int(input("Enter a number : "))
if num>1:
    for i in range(2,num):
        if num%i ==0:
            print(num," is not a prime number")
            break
        else:
            print(num," is a prime number")
            

Enter a number : 3
3  is a prime number


In [2]:
# program to make a simple calculator
def add(x,y):
    return x+y
def subtract(x,y):
    return x-y
def multiply(x,y):
    return x*y
def division(x,y):
    return x/y

print("Select operation")
print("1.Add")
print("2.Subtract")
print("3.Multiply")
print("4.Divide")

choice= input("Enter choice(1/2/3/4) : ")
num1= int(input("Enter first number : "))
num2= int(input("Enter second number : "))

if choice=='1':
    print(num1, "+", num2, "=", add(num1,num2))
if choice=='2':
    print(num1, "-", num2, "=", subtract(num1,num2))
if choice=='3':
    print(num1, "*", num2, "=", multiply(num1,num2))
if choice=='4':
    print(num1, "/", num2, "=", division(num1,num2))
else:
    print("Invalid input")
    

Select operation
1.Add
2.Subtract
3.Multiply
4.Divide
Enter choice(1/2/3/4) : 3
Enter first number : 34
Enter second number : 45
34 * 45 = 1530
Invalid input


In [ ]:
#program to find the factorial of a number

def Factorial(num):
    if num==1:
        return num
    else:
        return num* Factorial(num-1)

num= int(input("Enter a number : "))
if num<1:
    print(num, "Factorial cannot be found for negative values")
elif num==0:
    print("Factorial of zero is 1")
else:
    print(Factorial(num))

    

In [10]:
import math
print(math.sqrt(16))

4.0


In [20]:
# program to swap numbers

n1= int(input("Enter first number : "))
n2= int(input("Enter second number : "))
temp= n1
n1=n2
n2= temp
print('the value of n1 after swapping: {}'.format(n1))
print('the value of n2 after swapping: {}'.format(n2))



Enter first number : 34
Enter second number : 56
the value of n1 after swapping: 56
the value of n2 after swapping: 34


In [36]:
# program to print any random number

import random
print(random.randint(0,100))

60


In [40]:
# program to check a number is positive, negative or zero

num= int(input(" Enter a number : "))
if num<0:
    print(num," is negative")
elif num==0:
    print("Zero")
else:
    print(num," is positive number")

 Enter a number : 5
5  is positive number


In [49]:
# Leap year program
year= int(input("Enter year : "))
if (year%4==0 and year%100!=0) or (year%400==0):
    print(year, " is a Leap year")
else:
    print(year, " is not a Leap year")

Enter year : 2017
2017  is not a Leap year


In [54]:
# Largest num program
n1= int(input(" Enter first number : "))
n2= int(input(" Enter second number : "))
n3= int(input(" Enter third number : "))
if n1>n2 and n1>n3:
    print(n1," is the greatest number")
elif n2>n1 and n2>n3:
    print(n2," is the greatest number")
else:
    print(n3," is the greatest number")

 Enter first number : 1234
 Enter second number : 456789
 Enter third number : 456789
456789  is the greatest number


In [58]:
# program to print multiplication table
num= int(input("Enter table number : "))
for i in range(0,13):
    print(num,'*',i,'=',num*i)

Enter table number : 6
6 * 0 = 0
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
6 * 10 = 60
6 * 11 = 66
6 * 12 = 72


In [63]:
num= int(input("Enter number"))
if num%10 ==0:
    print(num," is a factor of 10")
else:
    print(num, " is not a factor of 10")

Enter number230
230  is a factor of 10


In [69]:
# program to check the numbers exists in the given range
num= int(input("Enter any number : "))
ub=200
lb=50
if num>=lb and num<=ub:
    print(num," exists in the range")
else:
    print(num," doesnt exist in the range")

Enter any number : 200
200  exists in the range


In [73]:
num= 98765432109875365226464849565920947856385009876542345677654567654345678765434567
print(len(str(num)))

80


In [77]:
#program to print nano seconds in the given year
year= int(input("Enter year : "))
if (year%4==0 and year%100!=0) or (year%400==0):
    print(366*24*60*60*(10**9))
else:
    print(365*24*60*60*(10**9))

Enter year : 1996
31622400000000000


In [80]:
# program to print reverse string

def reverseString(s):
    return s[::-1]

print(reverseString("Priya"))

ayirP


In [81]:
def reverseString(s):
    return s[::-1]

print(reverseString("Rajini Devi"))

iveD inijaR


In [82]:
def reverseString(s):
    return s[::-1]
print(reverseString("Vishnu Murthy"))

yhtruM unhsiV


In [83]:
def reverseString(s):
    return s[::-1]

print(reverseString("Pepeakayala"))

alayakaepeP


In [84]:
def countDigits(num):
    return (len(str(num)))

countDigits("Lashitha")

8

In [85]:
def countdigits(num):
    return (len(str(num)))

countdigits("Pepakayala")

10

In [2]:
# program to print n natural numbers

def nNaturalNumbers(n):
    counter=0
    while counter<=n:
        print(counter, end=" ")
        counter= counter+1
    return

nNaturalNumbers(100)

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 

In [8]:
# program to print numbers in a reverse range

def reverserange(a,b):
    for i in range(b,a-1,-1):
        print(i, end=" ")
    return
reverseRange(0,100)

100 99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0 

In [10]:
def reverserange(start,end):
    for value in range(end,start-1,-1):
        print(value, end=" ")
    return
reverseRange(0,25)

25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0 

In [16]:
def reverseodd(a,b):
    for i in range(b,a-1,-1):
        if i%2!=0:
            print(i,end=" ")
    return

reverseodd(1,26)
    

25 23 21 19 17 15 13 11 9 7 5 3 1 

In [22]:
# program to print the number of days in the given range of years

def numberofdays(startyear,endyear):
    sum=0
    for year in range(startyear, endyear+1):
        if (year%4==0 and year%100!=0) or (year%400==0):
            sum= sum+366
        else:
            sum= sum+365
    return sum

numberofdays(2019,2020)

731

In [36]:
def generateleapyear(startyear,endyear):
     for year in range(startyear, endyear+1):
        if (year%4==0 and year%100!=0) or (year%400==0):
            print(year, end=" ")
     return 
 
generateleapyear(2020,2050)
    

2020 2024 2028 2032 2036 2040 2044 2048 

In [39]:
import numpy as np
li = [1,2,3, 'z']
a = np.array(li)
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
m3= np.random.randint(0,2,size=(3,3,3,3))
m3[2][2][2][1]

1

In [45]:
m3.ndim
m3.size
m3.shape
m3.dtype
m3.itemsize
m3.nbytes

324

In [46]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [48]:
import numpy as np
M= np.ones((3,3))
print("Matrix M:\n",M)

Matrix M:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
import numpy as np
M= np.ones((2,2))
print("Matrix M:\n",M)

Matrix M:
 [[1. 1.]
 [1. 1.]]


In [5]:
import pandas as pd
internal1 = {'s1':21, 's2':18, 's3':24}
internal1 = pd.Series(internal1)
internal2 = {'s1':15, 's2':18, 's3':12}
internal2 = pd.Series(internal2)
internal2

s1    15
s2    18
s3    12
dtype: int64