In [1]:
filepath = 'DataFiles/Income.csv'
import pandas as pd
def readCSVdata(filepath):
    return pd.read_csv(filepath)

readCSVdata(filepath)

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

### Numpy Library

- Processing N-Dimensional arrays


In [2]:
import numpy as np
li=[1,2,3,'z']
a=np.array(li)
b=np.arange(15)
b


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
m3= np.random.randint(0,2,size=(3,3,3,3))
m3[2][2][2][1]

0

In [4]:
m3.ndim
m3.size
m3.shape
m3.dtype
m3.itemsize
m3.nbytes


324

In [5]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
c=b.reshape(5,3)

In [8]:
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [9]:
d= c+1
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [10]:
import numpy as np
M= np.ones((3,3))
print("Matrix M:\n",M)

Matrix M:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Pandas¶

#### Use Cases
- Data Cleaning
- Data Transformation
- Data Analysis
- Notations

#### Notations

- DataFrames
- Series

In [11]:
import pandas as pd
internal1= {'s1':18, 's2':36, 's3':24}
internal1=pd.Series(internal1)
internal2= {'s1':26, 's2':14, 's3':23}
internal2=pd.Series(internal1)
internal2

s1    18
s2    36
s3    24
dtype: int64

In [12]:
final={'Internal1': internal1, 'Internal2': internal2}
final= pd.DataFrame(final)
final['Internal1']

s1    18
s2    36
s3    24
Name: Internal1, dtype: int64

In [13]:
final

Internal1  Internal2
s1         18         18
s2         36         36
s3         24         24

In [14]:
final.columns

Index(['Internal1', 'Internal2'], dtype='object')

In [15]:
final.values

array([[18, 18],
       [36, 36],
       [24, 24]], dtype=int64)

In [17]:
final.values[2]

array([25, 24], dtype=int64)

In [16]:
final.values[2,0]= 25
final.values[2][0]

25

In [18]:
for row in final.values:
    print('Internal1 -', row[0],',Internal2 -', row[1])

Internal1 - 18 ,Internal2 - 18
Internal1 - 36 ,Internal2 - 36
Internal1 - 25 ,Internal2 - 24


In [19]:
final

Internal1  Internal2
s1         18         18
s2         36         36
s3         25         24

In [20]:
final.loc['s4'] = [20,18]
final


Internal1  Internal2
s1         18         18
s2         36         36
s3         25         24
s4         20         18

In [23]:
final.drop('s3')

Internal1  Internal2
s1         18         18
s2         36         36
s4         20         18

In [24]:
final

Internal1  Internal2
s1         18         18
s2         36         36
s3         25         24
s4         20         18

In [25]:
final= final.drop('s3')
final


Internal1  Internal2
s1         18         18
s2         36         36
s4         20         18

In [26]:
final.values[2]= [12,25]
final

Internal1  Internal2
s1         18         18
s2         36         36
s4         12         25

In [27]:
# program to Read CSV file data

import pandas as pd
filepath = 'DataFiles/Income.csv'
incomedf= pd.read_csv(filepath)
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [28]:
# Extract income of all states in 2013
#California : 57528

for row in incomedf.values:
    print(row[1], ':', row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [29]:
# Average income of Arizona
sum = 0
for i in range(2,11):
    sum += incomedf.values[2][i]
    
sum/len(incomedf.values[2][2:])

48967.88888888889

In [30]:
# Average income of all states in year 2012
sum = 0
for row in incomedf.values:
    sum += row[-2]
    
sum/len(incomedf.values)

50038.8

### Python Library for Data Analysis

#### Pandas- Data Analysis

- Series Object - one-dimensional data
- DataFrame Object - two-dimensional data
- Reading Data from CSV files into DataFrames
- Processing/Accessing DataFrames
   - Columns
   - Rows
- Updating DataFrames
- Writing DataFrame back to CSV files

In [35]:
# Function to read CSV data into a DataFrame and
# returns the DataFrame object

filepath= 'DataFiles/Income.csv'
import pandas as pd
def readCSVdata(filepath):
    return pd.read_csv(filepath)

readCSVdata(filepath)

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [38]:
incomedf = readCSVdata(filepath)
def printDataFrameColumns(df):
    columns= df.columns
    for column in columns:
        print(column, end= ' ')
    return

printDataFrameColumns(incomedf)

GEOID State 2005 2006 2007 2008 2009 2010 2011 2012 2013 

In [43]:
# Function to access a row based on a unique column value

def accessDataFrameRow(df,key):
    for row in df.values:
        if key in row:
            for item in row:
                print(item, end= ' ')
            print('\n')
    return

accessDataFrameRow(incomedf,'04000US06')

04000US06 California 51755 55319 55734 57014 56134 54283 53367 57020 57528 



In [44]:
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [47]:
# Accessing a unique value based on row, column info
# Income of a state in a given year

def getRowIndex(df,rowkey):
    for i in range(len(df.values)):
        if df.values[i][0]== rowkey or df.values[i][1] == rowkey:
            rowindex= i
    return rowindex

def getColumnIndex(df,columnkey):
    for i in range(len(df.columns)):
        if df.columns[i]== columnkey:
            columnindex=i
    return columnindex

def valueFromRowColumn(df,rowkeyy,columnkey):
    rowindex= getRowIndex(df, rowkey)
    columnindex= getColumnIndex(df, columnkey)
    return df. values[rowindex][columnindex]

valueFromRowColumn(incomedf, 'California', '2009')

NameError: name 'rowkey' is not defined

In [49]:
# Accessing a unique value based on row, column info
# Income of a state in a given year

def getRowIndex(df, rowkey):
    for i in range(len(df.values)):
        if df.values[i][0] == rowkey or df.values[i][1] == rowkey:
            rowindex = i
    return rowindex

def getColumnIndex(df, columnkey):
    for i in range(len(df.columns)):
        if df.columns[i] == columnkey:
            columnindex = i
    return columnindex

def valueFromRowColumn(df, rowkey, columnkey):
    rowindex = getRowIndex(df, rowkey)
    columnindex = getColumnIndex(df, columnkey)
    return df.values[rowindex][columnindex]

valueFromRowColumn(incomedf, 'California', '2009')

56134

In [50]:
# Function to update data based on rowkey and columnkey

def updateDataCellFromRowColumn(df,rowkey, columnkey, newdata):
    rowindex= getRowIndex(df, rowkey)
    columnindex = getColumnIndex(df, columnkey)
    row= df.values[rowindex]
    row[columnindex]= newdata
    df.loc[rowindex]= row
    return

updateDataCellFromRowColumn(incomedf, 'Arizona', '2007', 62993)
incomedf
    

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [51]:
accessDataFrameRow(incomedf, 62993)

04000US02 Alaska 55891 56418 62993 63989 61604 57848 57431 63648 61137 

04000US04 Arizona 45245 46657 62993 46914 45739 46896 48621 47044 50602 



In [53]:
# Function to add a new row of data to DataFrame

def addRowDataDataFrame(df,rowdata):
    lastrowindex = len(df.values)-1
    df.loc[lastrowindex+1]= rowdata
    return

rowdata= [1,2,3,4,5,56,13,14,313,12,0]
addRowDataDataFrame(incomedf, rowdata)
incomedf


GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   
5          1           2      3      4      5     56     13     14    313   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528  
5     12      0

In [54]:
# Program to delete a row in a DataFrame

def deleteRowDataFrame(df, rowkey):
    rowindex = getRowIndex(df, rowkey)
    return df.drop(rowindex)

incomedf= deleteRowDataFrame(incomedf, 1)
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [5]:
# Average income of all states from 2005 to 2013

filepath = 'Income.csv'
import pandas as pd
def readCSVdata(filepath):
    return pd.read_csv(filepath)

def average_income(income):
    print("Average income of every state from 2005 to 2013 \n")
    l=[]
    for i in income.values:
        l=l+[i]
        d={}
        dif=len(l[0])-2
        for i in range(0,len(l),1):
            if l[i][1] not in d:
                d[l[i][1]]=0
                for j in range(2,len(l[i]),1):
                    d[l[i][1]]+=l[i][j]
                    for key,values in d.items():
                        d[key]=d[key]//dif
    return d

In [3]:
# Program to count the number of each vowel in a string
vowels = 'aeiou'
ip_str = 'Only you'
ip_str = ip_str.casefold()
count = {}.fromkeys(vowels,0)
for char in ip_str:
   if char in count:
       count[char] += 1
print(count)

{'a': 0, 'e': 0, 'i': 0, 'o': 2, 'u': 1}


In [2]:
# Program to sort alphabetically the words form a string provided by the user
my_str = "May i speak to Ms.Lashitha Vishnu Priya"
words = my_str.split()
words.sort()
print("The sorted words are:")
for word in words:
   print(word)

    

The sorted words are:
May
Ms.Lashitha
Priya
Vishnu
i
speak
to


In [9]:
# Program to count the number of each consonant in a string
consonants = 'bcdfghjklmnpqrstvwxyz'
ip_str = 'its all about the journey not the destination'
ip_str = ip_str.casefold()
count = {}.fromkeys(consonants,0)
for char in ip_str:
   if char in count:
       count[char] += 1
print(count)

{'b': 1, 'c': 0, 'd': 1, 'f': 0, 'g': 0, 'h': 2, 'j': 1, 'k': 0, 'l': 2, 'm': 0, 'n': 4, 'p': 0, 'q': 0, 'r': 1, 's': 2, 't': 7, 'v': 0, 'w': 0, 'x': 0, 'y': 1, 'z': 0}


In [13]:
def averageincome(income):
    print("Average income of every state from 2005 to 2013\n")
    l= []
    for i in income.values:
        l= l+1
        d= {}
        dif= len(l[0])-2
        for i in range(0,len(1),1):
            if l[i][1] not in d:
                d[l[i][1]]=0
                for j in range(2,len(l[j]),1):
                    d[l[i][1]]+=l[i][j]
                    for key, values in d.items():
                        d[key]= d[key]//dif
                    return d
                
                