In [11]:
import numpy as np
li=[26,12,14,'g']
a= np.array(li)
b=np.arange(14)
b


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [14]:
m3= np.random.randint(0,2,size=(3,3,3,3))
m3[2][2][2][1]

1

In [17]:
m3.ndim
m3.size
m3.shape
m3.dtype
m3.itemsize
m3.nbytes

324

In [18]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


In [19]:
print(a)

['26' '12' '14' 'g']


In [29]:
import numpy as np
M = np.ones((3, 2))
print("Matrix M:\n",M)

Matrix M:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [34]:
import pandas as pd
internal1= {'s1': 26, 's2':14 ,'s3':23}
internal1= pd.Series(internal1)
internal2= {'s1': 12, 's2':35,'s3':11}
internal2=pd.Series(internal2)
internal2

s1    12
s2    35
s3    11
dtype: int64

In [35]:
final= {'Internal1':internal1, 'Internal2':internal2}
final= pd.DataFrame(final)
final['Internal1']

s1    26
s2    14
s3    23
Name: Internal1, dtype: int64

In [36]:
final

Internal1  Internal2
s1         26         12
s2         14         35
s3         23         11

In [37]:
final.columns

Index(['Internal1', 'Internal2'], dtype='object')

In [38]:
final.values

array([[26, 12],
       [14, 35],
       [23, 11]], dtype=int64)

In [39]:
final.values[2]

array([23, 11], dtype=int64)

In [41]:
final.values[1]

array([14, 35], dtype=int64)

In [45]:
final.values[2,0]=25
final.values[2][0]

25

In [46]:
for row in final.values:
    print('Internal1 - ',row[0],'Internal2 - ',row[1])

Internal1 -  26 Internal2 -  12
Internal1 -  14 Internal2 -  35
Internal1 -  25 Internal2 -  11


In [47]:
final

Internal1  Internal2
s1         26         12
s2         14         35
s3         25         11

In [48]:
final.loc['s4'] = [34,67]
final

Internal1  Internal2
s1         26         12
s2         14         35
s3         25         11
s4         34         67